name: bluez
version: 0.7.5

description:
  Provides a client to connect to BlueZ - the Linux Bluetooth stack.

homepage: https://github.com/canonical/bluez.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.6.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
  test_cov: ^1.0.1
