name: bluez
version: 0.1.2

description:
  Provides a client to connect to BlueZ - the Linux Bluetooth stack.

homepage: https://github.com/canonical/bluez.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.2.3

dev_dependencies:
  pedantic: ^1.9.0
