name: bluez
version: 0.7.8

description:
  Provides a client to connect to BlueZ - the Linux Bluetooth stack.

homepage: https://github.com/canonical/bluez.dart

environment:
  sdk: '>=2.15.0 <3.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1
